// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "types.proto" (package "types", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum types.ListType
 */
export enum ListType {
    /**
     * @generated from protobuf enum value: LIST_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: LIST_TYPE_LIST = 1;
     */
    LIST = 1,
    /**
     * @generated from protobuf enum value: LIST_TYPE_GRID = 2;
     */
    GRID = 2
}
