// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "types.proto" (package "types", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum types.ListType
 */
export enum ListType {
    /**
     * @generated from protobuf enum value: FILTER_UNKNOWN = 0;
     */
    FILTER_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: FILTER_LIST = 1;
     */
    FILTER_LIST = 1,
    /**
     * @generated from protobuf enum value: FILTER_GRID = 2;
     */
    FILTER_GRID = 2
}
