/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.3
 * source: types.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace types {
    export enum ListType {
        FILTER_UNKNOWN = 0,
        FILTER_LIST = 1,
        FILTER_GRID = 2
    }
}
