name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install
    - run: bun run build 